#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Commands Executed By Openbox Powermenu

## Options #############################################
if  [[ $1 = "--logout" ]]; then
	openbox --exit

elif  [[ $1 = "--suspend" ]]; then
	playerctl -a pause
	pamixer -m
	betterlockscreen --suspend

elif  [[ $1 = "--reboot" ]]; then
	systemctl reboot

elif  [[ $1 = "--shutdown" ]]; then
	systemctl poweroff

## Help Menu #############################################
else
echo "
Powermenu For Openbox Menu
Developed By - Aditya Shakya (@adi1090x)

Available options:
--logout	--suspend	--reboot	--shutdown
"
fi
