#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh
#fix for moving spotify to specific workspace
bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

bspc rule -r "*"

#BSPWM configuration
bspc config border_radius              8
bspc config border_width               2
bspc config window_gap                 10
bspc config top_padding                30
bspc config bottom_padding             10
bspc config left_padding               10
bspc config right_padding              10
bspc config single_monocle             false
bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config focus_follows_pointer      true
bspc config pointer_modifier           mod4
bspc config pointer_action1            move
bspc config pointer_action2            resize_side
bspc config pointer_action3            resize_corner
bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#7985D0"
bspc config active_border_color		"#7985D0"
bspc config focused_border_color	"#D7DD91"
bspc config presel_feedback_color	"#D7DD91"
bspc config urgent_border_color 	"#BF616A"

#Monitors
bspc monitor LVDS1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8 9 10

#Fullscreen applications
bspc rule -a inkscape state=fullscreen
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen

#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a feh state=floating
bspc rule -a Font-manager state=floating
bspc rule -a Nitrogen state=floating

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled
